### PR TITLE
replaced default favicon with new favicon

### LINKED ISSUE #7: Add new favicon.
Replace the favicon of the react app with a new either custom or from somewhere else should just go with the style.

### PR DESCRIPTION
**Pull request by VaibhavKambar7**
Fixes #7

### CODE REVIEW

**Comment by Umang375** [comment]
I am not able to view the icon right now, can you share the icon link so I can just see if it is okay?

**Comment by VaibhavKambar7** [comment]
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAflBMVEUAAAD///8dHR3T09PDw8P7+/v4+Pjz8/PJyclAQECbm5tJSUkZGRnw8PDs7OygoKCVlZXj4+Pd3d0RERG5ubkoKCgKCgp/f3+1tbW9vb2IiIjPz89ZWVl4eHhqamotLS2pqalfX19RUVFvb287Ozs0NDQjIyOPj49cXFw9PT3d3t4xAAAFfElEQVR4nO3d6XKqShQGUGYEBJlUQGRyynn/F7woqCg9kHuMbU59669d1N703E0lkvKvkwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAaRVmJDuHnKLWdzlR1li6KUnQsP8FZhLrc04MkFx3PqzWJIT/Svv6l5jrPAnnE9Jei43qZcqGPE2wllujIXuSQkBNsW6ojOrbJlHJ/OEbk347Vcxe80eP9e+P8n5ws2YRhqGqL4kj4OXNpCcqyYc/fHu635Zp7a4RG6I8izkN6grLsFSJi/g4nfQ55/ZjjMmEl2HbFg6DIp5lvCbPA4whZe+wMja2o4Kc4nojha829yHzBTlCWU/E9MVqW5NVyRBtDtHst7lVehp7gSdFZLxJNi6tTPf4TfjWhiXaS25haU2eKG6HN9CsO3EuIuhnMnoYQSdlQgzbW10IZN0G5em9OQ8fFQys0No8rEFbw4bXGK36Gm/dn1mtGXcjMBj9H1DZ6di35PJkQBCKSOysIM7Vh33vjlhl22I9NM36GnqAEc+IgaJ5ui8+YGbbRfHqGB0rzCq6rrCVzMSbLp67Y57bSjDbKp/0qq2Gsp8+SrtjHjjQldaI2dl2JwmTHPeuKfexssaMHFHfT4pYzlW+6DvuxMz6j+/SrrIkZHj511cbaEHTNlNtKu+kisnkZxpSjgZ+1px2snHWj5MSRhrt7MnciEpRyVkzVpUjJmS38/lFHzmiaijn+LlgxxV0Z9kxnfF2fxT7FCMRUoVSzgurb35qZYXjbiKzYJ1GC/q66wwp+0ZVZMjuYf3+YUtF7dSzqlEZhDZTX+Ys1SnrD3qVQD6MEHkPRN7eyeT2FOTI6WPb4OJtYi3oi8IiGsdia3U4odtQOlj7fuWTBOEfPlwSy6Nvbe/XMfUpj3jSjBzbVU45eXL8zoZEVtZOpg0XW0ibWokqKfV4vNl6/0tM9tdqJvlpzKOtJdz08WFyeCHWtUa53I2uXVUkcx9Vp54j/5xurLXEy0KvHVz+vnzfxrs+4Tlopy7Jcfsi3CpFP2jyMh/fjejikuonzGeFPko1qUU9It2dS48881zDdMNn+sm8sis1jNXonav1EpXUgZv9U6o/TNI5Vir+q6JW+ehsszSD+uw9E2oHGTtUwCEI1tbfOpyRprStNDcNwk5zyv9qprnJ7M5haTLWqhex8CaKDk381f5hNcHVoil2RW/Qp4GCHT4saPah+zWcK+yxWA8/zgnC2KMgV06iEgVkPBe0Nv+mw8O7R66ZKipp0U3yZWzJC4XdTrJ1fJfY6Jy+ylPEtsDZalGbUvZixEDzgRI6vXrtPUBXjJEffKVwmleyhPzL3+Ob42413svyH1mXGX0+9rCZvI11/OC4VzFs4by1uDbQqRvdGwemhGscXjISasTi3T+F4p/Um0ZawhTerwbq0pMfu3m65I/L2fkDYRp88/hmDvQXrINS7znUN50C4faSgnXBDOYS5X5HmzIuLtC814XZtJiTBI7UFev0rjzj9q5sXl5yz/wsha5sTPZ5N1065d0+X7jXh+lDMBSLztPdyXhppnLDdy3X4hGv8djjl77tejvnqL7fSDXOWk8/nHW2pckojlc33f7cfMQ6E5a7f0FditxfRtuaaN1V0L2PNjejVHPar99vlAOMuohfkvNubm+rtGa7Z4bfD+5H/FYm3ZV9tDKT8kF6MM4mFirRnt+Mz8yRJ3I9LO9rbM+SMk95esrgfIMiG/3szNJ1JGdrIEBkiQ2SIDOlca+p86E/LMH57hsVMZWkrR9qyi7SqfbtHiXmlzlIBG8RIYZlQ5FpK4pVqCdg7AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwN/4DxrPUpr02ZUBAAAAAElFTkSuQmCC

**Comment by VaibhavKambar7** [comment]
or you can check the icon from here

https://github.com/Umang375/Real_Social/pull/8/commits/6a0bef0d877c5638b153d702ac672b3cd9895d4b

**Comment by VaibhavKambar7** [comment]
Hey @Umang375, could you please check the icon link provided earlier? Let me know if it's acceptable. Thank you.

**Comment by Umang375** [comment]
I have seen your req and the changes made, the icon you have changed is good, and I will merge your request.

**Comment by VaibhavKambar7** [comment]
Thanks @Umang375

**Pull request merged**
